import { NextResponse } from 'next/server';
import { GoogleGenerativeAI, SchemaType, Schema } from '@google/generative-ai';

// Initialize the Gemini client
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

// ─── Google Doc Text Extraction ─────────────────────
async function fetchGoogleDocText(url: string): Promise<string> {
    try {
        // Extract Google Doc ID from URL
        const match = url.match(/\/d\/([a-zA-Z0-9_-]+)/);
        if (!match) return '';
        const docId = match[1];

        // Fetch as plain text via Google's export URL
        const exportUrl = `https://docs.google.com/document/d/${docId}/export?format=txt`;
        const response = await fetch(exportUrl, {
            headers: { 'User-Agent': 'Mozilla/5.0 (compatible; STEAMBot/1.0)' },
            redirect: 'follow',
        });

        if (!response.ok) return '';
        const text = await response.text();
        // Limit to ~15000 chars to stay within token limits
        return text.slice(0, 15000);
    } catch (e) {
        console.error('Failed to fetch Google Doc text:', e);
        return '';
    }
}

export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { googleDocUrl, abstractText } = body;

        if (!googleDocUrl && !abstractText) {
            return NextResponse.json(
                { error: 'Missing required fields (googleDocUrl or abstractText)' },
                { status: 400 }
            );
        }

        // Validate API Key
        if (!process.env.GEMINI_API_KEY) {
            return NextResponse.json(
                { error: 'Server missing GEMINI_API_KEY configuration.' },
                { status: 500 }
            );
        }

        let docText = abstractText || '';
        if (googleDocUrl) {
            const fetchedText = await fetchGoogleDocText(googleDocUrl);
            if (fetchedText) docText = fetchedText;
        }

        if (!docText || docText.trim().length < 50) {
            return NextResponse.json(
                { error: 'Not enough text could be extracted to perform an AI check.' },
                { status: 400 }
            );
        }

        const prompt = `### System Instructions for AI Plagiarism Detection
You are an expert AI detection tool designed to analyze academic writing. Your job is to estimate the percentage of the following text that was likely generated by an AI language model (like ChatGPT, Claude, Gemini, etc.) versus written by a human.

Look for signs of AI generation such as:
- Lack of "burstiness" (sentences all having similar length and structure)
- Lack of "perplexity" (highly predictable word choices)
- Overuse of transitional phrases (e.g., "Furthermore", "In conclusion", "It is important to note")
- Overly formal or generic academic tone lacking personal voice

**Student Document Content:**
<DOCUMENT>
${docText}
</DOCUMENT>

Analyze the text and return your best estimate as a single integer percentage from 0 to 100, where 0 means completely human-written, and 100 means completely AI-generated.`;

        const responseSchema: Schema = {
            type: SchemaType.OBJECT,
            properties: {
                ai_percentage: {
                    type: SchemaType.INTEGER,
                    description: "Estimated percentage (0-100) of the text that is AI-generated."
                },
                explanation: {
                    type: SchemaType.STRING,
                    description: "A brief one-sentence explanation of why this score was given."
                }
            },
            required: ["ai_percentage", "explanation"]
        };

        const model = genAI.getGenerativeModel({
            model: "gemini-1.5-flash",
            generationConfig: {
                temperature: 0.1,
                responseMimeType: "application/json",
                responseSchema: responseSchema,
            },
        });

        const result = await model.generateContent(prompt);
        const responseText = result.response.text();
        const parsedResponse = JSON.parse(responseText);

        return NextResponse.json({
            ai_percentage: parsedResponse.ai_percentage,
            explanation: parsedResponse.explanation
        });

    } catch (error: any) {
        console.error("AI Detect Error:", error);
        return NextResponse.json(
            { error: error.message || 'An error occurred during AI detection.' },
            { status: 500 }
        );
    }
}
